# Generated by Django 3.2.1 on 2021-05-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badwords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badword', models.CharField(max_length=30)),
            ],
        ),
    ]
