# Generated by Django 3.2.3 on 2021-06-01 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_badwords'),
        ('posts', '0010_alter_post_categories'),
    ]

    operations = [
    ]
