# Generated by Django 3.2.1 on 2021-06-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_merge_0007_badwords_0010_alter_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
